# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: AWS-CODEBUILD_DEMO-CICD

      - name: Deploy Website
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # GitHub repository where assets will be deployed (default current)
          repo: master
          build_dir: public 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
            
